"""The dynamic harness -- ARCHITECTURE-FINAL.md sec 1/7 ("dynamic/harness.py"): the
snapshot -> invoke -> snapshot -> evaluate loop over a live `adapters.base.Adapter`, driven by
`dynamic/probes.py`'s probe plan, producing `core.verdict.ClauseVerdict`s and writing
`report/findings.jsonl` (deliverable 6, the machine-readable conformance report format).

This module owns exactly one new piece of checker logic beyond what `adapters/contract_check.py`
already provides: `check_ignored_argument`, implementing the REVISED M-IGNARG definition (CLAUDE.md
build spec). It could not live in `adapters/contract_check.py`, whose two entry points both grade
a single (pre, post, args, result) tuple; Ignored Argument is decided across MULTIPLE calls that
vary one argument, so it belongs with the multi-invocation loop that produces those calls.

THE DEFINITION CHANGE, AND WHY. The old (pre-registration-era) rule required BOTH the post-state
AND the result to be invariant across an argument's varied values before reporting Ignored
Argument -- a conjunctive test. That rule cannot fire on FINDINGS-VERIFIED.md Finding 6:
AgentDojo's `reserve_car_rental` discards `end_time` from state (`reservation.end_time =
datetime.fromisoformat(start_time)`, never `end_time`) but ECHOES the caller's `end_time` verbatim
into its success string ("...has been made successfully." built from the local `end_time`
variable, not from state). Under the conjunctive rule, the varying RESULT blocks the verdict on
one of the taxonomy's own anchor findings -- the state genuinely doesn't depend on the argument,
which is exactly what "ignored" means, and the old rule refused to say so.

The new rule: Ignored Argument is decided on POST-STATE INVARIANCE ALONE. Whether the result also
disagrees with state is computed separately and reported as an AGGRAVATING SIGNAL alongside the
finding -- present in every `findings.jsonl` row this module writes for an `arg.*` clause id, never
folded into the verdict itself. See `check_ignored_argument` below.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Optional

from adapters.base import Adapter, ToolResult
from adapters.contract_check import check_effects, check_precondition_enforcement, to_result_binding
from adapters.tau2 import Tau2Adapter, Tau2AdapterError
from core.canonical import CanonicalConfig, canonical_equal, diff
from core.model import Contract
from core.verdict import ClauseVerdict, DefectClass, Verdict, Witness
from dynamic.probes import build_dynamic_probe_plan
from toy.adapter import ToyAdapter

__all__ = [
    "InvokeRecord",
    "check_ignored_argument",
    "run_contract",
    "run_all",
    "write_findings",
    "PROJECT_ROOT",
    "REPORT_PATH",
]

PROJECT_ROOT = Path(__file__).resolve().parent.parent
CONTRACTS_ROOT = PROJECT_ROOT / "spec" / "contracts"
REPORT_PATH = PROJECT_ROOT / "report" / "findings.jsonl"

# toy/bank.py's audit log carries a monotonic `seq` counter, deliberately analogous to a real
# benchmark's autogenerated id/timestamp field (see toy/bank.py's `_next_audit_entry` docstring).
# Masked here so it never manufactures a spurious "this argument affects state" verdict purely
# through call-count drift across probes that are otherwise unrelated to the audit log.
TOY_CANONICAL_CONFIG = CanonicalConfig(volatile_paths=("state.audit_log.[].seq",))

# tau2 tool name -> in-scope domain, for the two contracts this milestone ships
# (spec/contracts/tau2/{cancel_reservation,refuel_data}.yaml). Not a general tool->domain
# resolver -- adapters.tau2.Tau2Adapter.source() already documents that several tau2 tool names
# recur across domains and must be disambiguated by the caller; this table is deliberately scoped
# to the tools this milestone has contracts for rather than guessing at the others.
TAU2_DOMAIN_BY_TOOL = {"cancel_reservation": "airline", "refuel_data": "telecom"}


# =================================================================================================
# The snapshot/invoke/snapshot primitive, used by every probe kind below.
# =================================================================================================


class InvokeRecord:
    """One fresh-env probe call and everything the checker needs from it: the pre/post snapshots,
    the args, the canonicalized `result` binding (see `adapters.contract_check.to_result_binding`),
    whether the call succeeded, and the raw adapter error string when it did not."""

    __slots__ = ("args", "pre", "post", "result", "success", "error")

    def __init__(self, args: dict, pre: Any, post: Any, result: Any, success: bool, error: Optional[str]):
        self.args = args
        self.pre = pre
        self.post = post
        self.result = result
        self.success = success
        self.error = error


def _invoke_fresh(adapter: Adapter, scenario_id: str, tool: str, args: dict) -> InvokeRecord:
    """fresh_env -> snapshot -> invoke -> snapshot, in a brand-new environment instance every
    time. Each probe call is graded against its OWN fresh pre-snapshot rather than a shared,
    possibly-drifted one -- the same pattern tests/test_tau2_adapter.py's Gate 1a/1b tests use by
    hand, generalised here so the harness never has to reason about accumulated state from an
    earlier probe in the same run."""
    env = adapter.fresh_env(scenario_id)
    pre = adapter.snapshot(env)
    tr: ToolResult = adapter.invoke(env, tool, args)
    post = adapter.snapshot(env)
    result = to_result_binding(tr.raw, tr.success, tr.error)
    return InvokeRecord(args=args, pre=pre, post=post, result=result, success=tr.success, error=tr.error)


# =================================================================================================
# check_ignored_argument -- the one new piece of checker logic this milestone adds.
# =================================================================================================


def check_ignored_argument(
    arg_name: str,
    calls: list,
    *,
    cfg: Optional[CanonicalConfig] = None,
) -> tuple:
    """M-IGNARG under the revised definition (see module docstring): Ignored Argument iff the
    canonicalized post-state is IDENTICAL across every successful call in `calls` despite each
    call using a different value of `arg_name`, all other arguments held fixed. `calls` is a list
    of `InvokeRecord`s that differ only in `arg_name`'s value (dynamic/probes.py's
    `generate_ignored_argument_probes` builds exactly this shape).

    Returns `(ClauseVerdict, aggravation)`. `aggravation` is a plain dict, never folded into the
    ClauseVerdict itself (core/verdict.py's lattice is deliberately not extended for this -- the
    aggravating signal is call-set-level evidence, reported alongside a finding in
    findings.jsonl, not a property of the clause verdict lattice):

        {"aggravating_signal": "result_disagrees_with_state" | None,
         "n_successful_variants": int,
         "argument_values_tried": [...]}   # only populated on a VIOLATES verdict

    Needs at least two SUCCESSFUL calls using at least two DISTINCT values of `arg_name` to say
    anything -- a call that raised never reaches the tool's effect code, so its post-state
    trivially equals pre regardless of what `arg_name` was, and admitting a failed call into the
    comparison would manufacture an Ignored Argument verdict out of an argument that in fact
    determined success or failure (the opposite of ignored). Fewer than two such calls ->
    UNTESTABLE / no_observable_state.
    """
    clause_id = f"arg.{arg_name}"
    cfg = cfg or CanonicalConfig()

    successful = [c for c in calls if c.success]
    seen_values: list = []
    distinct: list = []
    for c in successful:
        v = c.args[arg_name]
        if v in seen_values:
            continue
        seen_values.append(v)
        distinct.append(c)

    if len(distinct) < 2:
        verdict = ClauseVerdict(verdict=Verdict.UNTESTABLE, clause_id=clause_id, reason_code="no_observable_state")
        return verdict, {"aggravating_signal": None, "n_successful_variants": len(distinct)}

    reference = distinct[0]
    state_invariant = all(canonical_equal(reference.post, c.post, cfg) for c in distinct[1:])

    if not state_invariant:
        verdict = ClauseVerdict(verdict=Verdict.CONFORMS, clause_id=clause_id)
        return verdict, {"aggravating_signal": None, "n_successful_variants": len(distinct)}

    # Post-state does not depend on arg_name across every successful variant tried: Ignored
    # Argument, decided on state alone. The aggravating signal is a SEPARATE question, asked only
    # now: does the RESULT vary even though state does not? FINDINGS-VERIFIED.md Finding 6's
    # exact shape (state pinned to start_time, the return string still echoes the discarded
    # end_time) is `result_disagrees_with_state` here.
    result_disagrees = not all(canonical_equal(reference.result, c.result, cfg) for c in distinct[1:])

    verdict = ClauseVerdict(
        verdict=Verdict.VIOLATES,
        clause_id=clause_id,
        defect_class=DefectClass.IGNORED_ARGUMENT,
        witness=Witness(
            args=dict(reference.args),
            diff=diff(reference.pre, reference.post, cfg),
            result=reference.result,
        ),
    )
    aggravation = {
        "aggravating_signal": "result_disagrees_with_state" if result_disagrees else None,
        "n_successful_variants": len(distinct),
        "argument_values_tried": [c.args[arg_name] for c in distinct],
    }
    return verdict, aggravation


# =================================================================================================
# The per-contract loop.
# =================================================================================================


def _witness_to_json(w: Optional[Witness]) -> Optional[dict]:
    if w is None:
        return None
    return {"args": w.args, "diff": w.diff, "result": w.result}


def _row(*, kind: str, contract: Contract, scenario_id: str, cv: ClauseVerdict, probe_origin: str, extra: Optional[dict] = None) -> dict:
    row = {
        "kind": kind,
        "benchmark": contract.benchmark,
        "tool": contract.tool,
        "commit": contract.commit,
        "scenario_id": scenario_id,
        "clause_id": cv.clause_id,
        "verdict": cv.verdict.value,
        "defect_class": cv.defect_class.value if cv.defect_class else None,
        "reason_code": cv.reason_code,
        "witness": _witness_to_json(cv.witness),
        "probe_origin": probe_origin,
    }
    if extra:
        row.update(extra)
    return row


def run_contract(
    adapter: Adapter,
    contract: Contract,
    scenario_id: str,
    *,
    cfg: Optional[CanonicalConfig] = None,
    seed: int = 0,
) -> list:
    """The full milestone-2 build-spec loop for one contract against one live adapter: generate
    the probe plan from a fresh pre-snapshot, invoke every probe against its OWN fresh
    environment, evaluate every resulting call against the contract with
    `adapters.contract_check` (effects, precondition enforcement) plus this module's own
    `check_ignored_argument`, and return the `findings.jsonl` rows (see `_row`). Never raises on
    a probe-generation gap -- an effect clause with no happy-path probe, or an argument with too
    few distinct successful variants, is reported as an UNTESTABLE row rather than silently
    dropped, so the sec-4.3 probe-gap accounting in `detector_analysis_plan.md` has something to
    count."""
    cfg = cfg or CanonicalConfig()
    seed_env = adapter.fresh_env(scenario_id)
    pre0 = adapter.snapshot(seed_env)
    plan = build_dynamic_probe_plan(contract, pre0, seed=seed)

    rows: list = []

    # -- preconditions: satisfy probes feed check_effects (more observations of the effect
    #    clauses, each tagged by the precondition-satisfying probe that drove it); violate probes
    #    feed check_precondition_enforcement. --------------------------------------------------
    #
    #    A "satisfy" probe only guarantees ONE clause holds -- it says nothing about the tool's
    #    OTHER declared preconditions, which the same call may still violate. A call that raised
    #    never reached the tool's effect code, so post == pre; running check_effects on that pair
    #    would grade every effect predicate against a no-op and manufacture a false VIOLATES
    #    (typically Phantom Effect, since every effect clause fails identically) out of a tool
    #    that never had a chance to apply them. check_effects is therefore only ever called on a
    #    call that actually succeeded -- a failed satisfy-probe call contributes nothing here (the
    #    happy-path probe below is the real, joint-satisfying source of effect coverage).
    for probe in plan.precondition_probes:
        rec = _invoke_fresh(adapter, scenario_id, contract.tool, probe.args)
        if probe.origin.startswith("precondition_satisfy:"):
            if rec.success:
                for cv in check_effects(contract, rec.pre, rec.post, rec.args, rec.result, cfg=cfg):
                    rows.append(_row(kind="effect", contract=contract, scenario_id=scenario_id, cv=cv, probe_origin=probe.origin))
        elif probe.origin.startswith("precondition_violate:"):
            cv = check_precondition_enforcement(contract, rec.pre, rec.post, rec.args, rec.result, rec.error, cfg=cfg)
            if cv is not None:
                rows.append(_row(kind="precondition_enforcement", contract=contract, scenario_id=scenario_id, cv=cv, probe_origin=probe.origin))

    # -- effects: the happy-path probe. Guarded the same way -- the probe was BUILT to satisfy
    #    every precondition against the contract's own predicates, but the contract's predicates
    #    are a translation of the real implementation's guards and can diverge from them (that
    #    divergence is itself something worth surfacing, not papering over with a false VIOLATES
    #    on every effect clause). ---------------------------------------------------------------
    if plan.effect_probe is not None:
        rec = _invoke_fresh(adapter, scenario_id, contract.tool, plan.effect_probe.args)
        if rec.success:
            for cv in check_effects(contract, rec.pre, rec.post, rec.args, rec.result, cfg=cfg):
                rows.append(_row(kind="effect", contract=contract, scenario_id=scenario_id, cv=cv, probe_origin=plan.effect_probe.origin))
        else:
            for ec in contract.effects:
                cv = ClauseVerdict(verdict=Verdict.UNTESTABLE, clause_id=ec.id, reason_code="no_observable_state")
                rows.append(
                    _row(
                        kind="effect", contract=contract, scenario_id=scenario_id, cv=cv,
                        probe_origin="effect_happy_path_call_failed", extra={"call_error": rec.error},
                    )
                )
    else:
        # A probe gap, not a clause gap: every effect clause covers real behaviour, but this
        # module's own search never found a joint argument assignment satisfying every
        # precondition. Reported per clause so it is countable.
        for ec in contract.effects:
            cv = ClauseVerdict(verdict=Verdict.UNTESTABLE, clause_id=ec.id, reason_code="no_observable_state")
            rows.append(_row(kind="effect", contract=contract, scenario_id=scenario_id, cv=cv, probe_origin="effect_happy_path_not_found"))

    # -- Ignored Argument: one check_ignored_argument call per effective argument that got a
    #    usable variant set. --------------------------------------------------------------------
    covered_args = set()
    for arg_name, variant_probes in plan.ignored_argument_probes.items():
        covered_args.add(arg_name)
        calls = [_invoke_fresh(adapter, scenario_id, contract.tool, p.args) for p in variant_probes]
        cv, aggravation = check_ignored_argument(arg_name, calls, cfg=cfg)
        rows.append(
            _row(
                kind="ignored_argument",
                contract=contract,
                scenario_id=scenario_id,
                cv=cv,
                probe_origin=f"ignored_argument:{arg_name}",
                extra=aggravation,
            )
        )
    for arg_name, spec in contract.signature.args.items():
        if spec.effective and arg_name not in covered_args:
            cv = ClauseVerdict(verdict=Verdict.UNTESTABLE, clause_id=f"arg.{arg_name}", reason_code="no_observable_state")
            rows.append(
                _row(
                    kind="ignored_argument",
                    contract=contract,
                    scenario_id=scenario_id,
                    cv=cv,
                    probe_origin="ignored_argument_probe_not_found",
                    extra={"aggravating_signal": None, "n_successful_variants": 0},
                )
            )

    return rows


# =================================================================================================
# End-to-end runner: toy (all shipped contracts) + tau2 (the two shipped contracts).
# =================================================================================================


def _iter_toy_contracts():
    for path in sorted((CONTRACTS_ROOT / "toy").glob("*.yaml")):
        yield Contract.from_yaml(path), "default"


def _iter_tau2_contracts():
    for path in sorted((CONTRACTS_ROOT / "tau2").glob("*.yaml")):
        if path.suffix != ".yaml":
            continue
        contract = Contract.from_yaml(path)
        domain = TAU2_DOMAIN_BY_TOOL.get(contract.tool)
        if domain is None:
            continue  # not a tool this milestone has a domain mapping for -- skip, don't guess
        yield contract, domain


def run_all(*, seed: int = 0) -> list:
    """Run every shipped toy contract against `ToyAdapter` and every mapped tau2 contract against
    `Tau2Adapter`, returning the combined `findings.jsonl` rows. If the tau2 venv is not
    provisioned, records one `adapter_unavailable` row instead of failing the whole run -- mirrors
    `tests/test_tau2_adapter.py`'s skip discipline, but as data rather than a test skip, since this
    is meant to run outside `unittest` too."""
    rows: list = []

    toy_adapter = ToyAdapter()
    for contract, scenario_id in _iter_toy_contracts():
        rows.extend(run_contract(toy_adapter, contract, scenario_id, cfg=TOY_CANONICAL_CONFIG, seed=seed))

    try:
        tau2_adapter = Tau2Adapter()
    except Tau2AdapterError as e:
        rows.append({"kind": "adapter_unavailable", "benchmark": "tau2-bench", "detail": str(e)})
        return rows
    try:
        for contract, domain in _iter_tau2_contracts():
            rows.extend(run_contract(tau2_adapter, contract, domain, seed=seed))
    finally:
        tau2_adapter.close()

    return rows


def write_findings(rows: list, out_path: Path = REPORT_PATH) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as fh:
        for row in rows:
            fh.write(json.dumps(row, sort_keys=True) + "\n")


def main(argv: Optional[list] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--out", type=Path, default=REPORT_PATH, help="output JSONL path")
    parser.add_argument("--seed", type=int, default=0, help="probe-plan search seed")
    args = parser.parse_args(argv)

    rows = run_all(seed=args.seed)
    write_findings(rows, args.out)
    print(f"wrote {len(rows)} rows to {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
