"""Canonicalization and diffing. PREDICATE-GRAMMAR.md sec 4.

1. Mappings serialize with sorted keys -- insertion order is never semantic.
2. Volatile fields (timestamps, autogenerated ids, monotonic counters) are masked by a
   sentinel. The mask list is frame-path patterns, matched with require_match=False since a
   volatile pattern need not apply to every snapshot shape.
3. Numbers (int and float alike, but never bool -- see below) compare at a declared tolerance;
   default is exact (tolerance 0.0).
4. Sequences are order-sensitive by default; an explicit list of frame-path patterns opts
   specific paths into order-insensitive (multiset) comparison.

CanonicalConfig.to_dict()/from_dict() keep the config JSON-serializable so it can be printed
into the artifact -- a volatile field is a place the checker is deliberately blind, and that
has to be auditable.

Tolerance is a COMPARISON concern, not a canonicalization concern. `canonicalize()` never
mutates a numeric value -- earlier it bucketed floats with `round(node / tol) * tol`, which is
quantization, not tolerance: two values 2e-6 apart can land in different buckets right at a
bucket edge (0.014999 and 0.015001 at tol=0.01 canonicalize to 0.01 and 0.02, a difference
*larger* than the declared tolerance was supposed to permit), and it only ever matched
`isinstance(node, float)`, so an int and an equal float diverged under nonzero tolerance instead
of comparing equal. `canonical_equal(a, b, cfg)` is tolerance-aware equality over two
already-shaped values (or two raw snapshots -- it canonicalizes both first): a number is `abs(a
- b) <= tol` with int and float treated identically as numbers, and `bool` is deliberately never
treated as a number here (it is a subclass of `int` in Python, but a flag flipping True/False
must never be forgiven by a numeric tolerance) -- it always compares by `==`. `diff()` is built
on the same comparison so a witness never reports a within-tolerance pair as a change.
"""
from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any

from core.frame import match_paths

VOLATILE_SENTINEL = "☃MASKED☃"

_MISSING = object()


@dataclass(frozen=True)
class CanonicalConfig:
    volatile_paths: tuple = ()
    float_tolerance: float = 0.0
    unordered_paths: tuple = ()

    def to_dict(self) -> dict:
        return {
            "volatile_paths": list(self.volatile_paths),
            "float_tolerance": self.float_tolerance,
            "unordered_paths": list(self.unordered_paths),
        }

    @staticmethod
    def from_dict(d: dict) -> "CanonicalConfig":
        return CanonicalConfig(
            volatile_paths=tuple(d.get("volatile_paths", [])),
            float_tolerance=d.get("float_tolerance", 0.0),
            unordered_paths=tuple(d.get("unordered_paths", [])),
        )


def _matched_path_set(patterns: tuple, snapshot: Any) -> set:
    out: set = set()
    for p in patterns:
        out.update(match_paths(p, snapshot, require_match=False))
    return out


def canonicalize(snapshot: Any, config: CanonicalConfig) -> Any:
    """Structural canonicalization only: sorted mapping keys, volatile masking, and stable
    ordering of paths declared unordered. Never mutates a number -- see module docstring. Two
    canonicalized structures being `==` is therefore an EXACT-equality check; use
    `canonical_equal()` when `config.float_tolerance` is nonzero and near-enough numbers must
    compare equal."""
    volatile = _matched_path_set(config.volatile_paths, snapshot)
    unordered = _matched_path_set(config.unordered_paths, snapshot)
    return _canon(snapshot, (), volatile, unordered)


def _canon(node: Any, path: tuple, volatile: set, unordered: set) -> Any:
    if path in volatile:
        return VOLATILE_SENTINEL
    if isinstance(node, dict):
        return {k: _canon(node[k], path + (k,), volatile, unordered) for k in sorted(node.keys())}
    if isinstance(node, list):
        items = [_canon(v, path + (i,), volatile, unordered) for i, v in enumerate(node)]
        if path in unordered:
            items = sorted(items, key=_sort_key)
        return items
    return node


def _sort_key(v: Any) -> str:
    # Best-effort deterministic ordering for heterogeneous JSON-shaped values -- used only to
    # give an order-insensitive sequence a stable canonical order for comparison.
    return json.dumps(v, sort_keys=True, default=str)


def _is_number(v: Any) -> bool:
    # bool is a subclass of int in Python but is never treated as a number here -- a flag flip
    # must not be forgiven by a numeric tolerance. See module docstring.
    return isinstance(v, (int, float)) and not isinstance(v, bool)


def _values_equal(a: Any, b: Any, tol: float) -> bool:
    """Leaf-level equality: two numbers (int or float, never bool) are equal within `tol`;
    everything else (including bool, str, None, and the `_MISSING` sentinel used by `_diff`)
    falls back to plain `==`."""
    if _is_number(a) and _is_number(b):
        return abs(a - b) <= tol
    return a == b


def canonical_equal(a: Any, b: Any, config: "CanonicalConfig | None" = None) -> bool:
    """Tolerance-aware structural equality between two raw (not yet canonicalized) snapshots or
    values: canonicalize both under `config`, then compare recursively with `_values_equal` at
    the leaves instead of Python's `==`. This is the replacement for the old
    `canonicalize(a, cfg) == canonicalize(b, cfg)` idiom, which -- once canonicalize() stopped
    quantizing floats -- would go back to exact comparison and silently drop tolerance
    entirely."""
    cfg = config or CanonicalConfig()
    ca = canonicalize(a, cfg)
    cb = canonicalize(b, cfg)
    return _struct_equal(ca, cb, cfg.float_tolerance)


def _descend(node: Any, path: tuple) -> Any:
    """Walk `path` (a tuple of dict keys / list indices, as produced by core.frame.match_paths)
    into an already-canonicalized `node`. Returns `_MISSING` -- never raises -- the instant a
    step does not resolve, so a concrete path that exists in one snapshot but not the other
    (a key added or removed by the call) degrades to a clean unequal comparison downstream
    rather than a KeyError/IndexError/TypeError escaping this module."""
    for key in path:
        if isinstance(node, dict) and key in node:
            node = node[key]
        elif isinstance(node, list) and isinstance(key, int) and 0 <= key < len(node):
            node = node[key]
        else:
            return _MISSING
    return node


def canonical_equal_at(pre: Any, post: Any, path: tuple, config: "CanonicalConfig | None" = None) -> bool:
    """Tolerance- and volatility-aware equality of the SUBTREE at `path` between two RAW (not yet
    canonicalized) snapshots -- what `dynamic.harness.check_frame` needs to grade one concrete
    frame-path match. `config.volatile_paths`/`unordered_paths` are frame-path patterns rooted at
    the snapshot's own root (e.g. 'state.audit_log.[].seq'), exactly like `canonical_equal`'s and
    `diff`'s -- so this canonicalizes the FULL `pre`/`post` snapshots first (masking/reordering
    resolves correctly regardless of where `path` cuts into the tree) and only then descends
    `path` into each already-canonicalized tree, comparing the two extracted subtrees with the
    same tolerance-aware leaf rule `canonical_equal` uses (`_struct_equal`). Canonicalizing the
    extracted subtree in isolation instead -- the naive alternative -- would silently break any
    volatile_paths entry nested under `path`, since `_matched_path_set` would then try to match
    that pattern against the subtree's own (differently-rooted) shape."""
    cfg = config or CanonicalConfig()
    cpre = canonicalize(pre, cfg)
    cpost = canonicalize(post, cfg)
    return _struct_equal(_descend(cpre, path), _descend(cpost, path), cfg.float_tolerance)


def _struct_equal(a: Any, b: Any, tol: float) -> bool:
    if isinstance(a, dict) and isinstance(b, dict):
        return set(a) == set(b) and all(_struct_equal(a[k], b[k], tol) for k in a)
    if isinstance(a, list) and isinstance(b, list):
        return len(a) == len(b) and all(_struct_equal(x, y, tol) for x, y in zip(a, b))
    return _values_equal(a, b, tol)


def diff(pre: Any, post: Any, config: CanonicalConfig | None = None) -> dict:
    """Structural diff between pre and post, after canonicalizing both. Suitable for a finding
    witness: {dotted.path.string: {"pre": ..., "post": ...}} for every leaf that differs. Leaf
    comparison is tolerance-aware (`_values_equal`), so a pair within `config.float_tolerance`
    is never reported as a change. Lists of differing length walk index-aligned over the common
    prefix; any tail elements beyond the shorter list's length are reported individually (one
    diff entry per added/removed element), not folded into one entry containing both full
    lists."""
    cfg = config or CanonicalConfig()
    cpre = canonicalize(pre, cfg)
    cpost = canonicalize(post, cfg)
    changes: dict = {}
    _diff(cpre, cpost, (), changes, cfg.float_tolerance)
    return changes


def _diff(a: Any, b: Any, path: tuple, changes: dict, tol: float) -> None:
    if isinstance(a, dict) and isinstance(b, dict):
        for k in sorted(set(a) | set(b)):
            _diff(a.get(k, _MISSING), b.get(k, _MISSING), path + (k,), changes, tol)
        return
    if isinstance(a, list) and isinstance(b, list):
        common = min(len(a), len(b))
        for i in range(common):
            _diff(a[i], b[i], path + (i,), changes, tol)
        for i in range(common, len(a)):  # removed tail elements, individually
            _diff(a[i], _MISSING, path + (i,), changes, tol)
        for i in range(common, len(b)):  # added tail elements, individually
            _diff(_MISSING, b[i], path + (i,), changes, tol)
        return
    if not _values_equal(a, b, tol):
        key = ".".join(str(p) for p in path) or "."
        changes[key] = {
            "pre": None if a is _MISSING else a,
            "post": None if b is _MISSING else b,
        }
