"""Canonicalization and diffing. PREDICATE-GRAMMAR.md sec 4.

1. Mappings serialize with sorted keys -- insertion order is never semantic.
2. Volatile fields (timestamps, autogenerated ids, monotonic counters) are masked by a
   sentinel. The mask list is frame-path patterns, matched with require_match=False since a
   volatile pattern need not apply to every snapshot shape.
3. Floats compare at a declared tolerance; default is exact (tolerance 0.0).
4. Sequences are order-sensitive by default; an explicit list of frame-path patterns opts
   specific paths into order-insensitive (multiset) comparison.

CanonicalConfig.to_dict()/from_dict() keep the config JSON-serializable so it can be printed
into the artifact -- a volatile field is a place the checker is deliberately blind, and that
has to be auditable.
"""
from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any

from core.frame import match_paths

VOLATILE_SENTINEL = "☃MASKED☃"

_MISSING = object()


@dataclass(frozen=True)
class CanonicalConfig:
    volatile_paths: tuple = ()
    float_tolerance: float = 0.0
    unordered_paths: tuple = ()

    def to_dict(self) -> dict:
        return {
            "volatile_paths": list(self.volatile_paths),
            "float_tolerance": self.float_tolerance,
            "unordered_paths": list(self.unordered_paths),
        }

    @staticmethod
    def from_dict(d: dict) -> "CanonicalConfig":
        return CanonicalConfig(
            volatile_paths=tuple(d.get("volatile_paths", [])),
            float_tolerance=d.get("float_tolerance", 0.0),
            unordered_paths=tuple(d.get("unordered_paths", [])),
        )


def _matched_path_set(patterns: tuple, snapshot: Any) -> set:
    out: set = set()
    for p in patterns:
        out.update(match_paths(p, snapshot, require_match=False))
    return out


def canonicalize(snapshot: Any, config: CanonicalConfig) -> Any:
    volatile = _matched_path_set(config.volatile_paths, snapshot)
    unordered = _matched_path_set(config.unordered_paths, snapshot)
    return _canon(snapshot, (), volatile, unordered, config.float_tolerance)


def _canon(node: Any, path: tuple, volatile: set, unordered: set, tol: float) -> Any:
    if path in volatile:
        return VOLATILE_SENTINEL
    if isinstance(node, dict):
        return {k: _canon(node[k], path + (k,), volatile, unordered, tol) for k in sorted(node.keys())}
    if isinstance(node, list):
        items = [_canon(v, path + (i,), volatile, unordered, tol) for i, v in enumerate(node)]
        if path in unordered:
            items = sorted(items, key=_sort_key)
        return items
    if isinstance(node, float) and tol > 0:
        return round(node / tol) * tol
    return node


def _sort_key(v: Any) -> str:
    # Best-effort deterministic ordering for heterogeneous JSON-shaped values -- used only to
    # give an order-insensitive sequence a stable canonical order for comparison.
    return json.dumps(v, sort_keys=True, default=str)


def diff(pre: Any, post: Any, config: CanonicalConfig | None = None) -> dict:
    """Structural diff between pre and post, after canonicalizing both. Suitable for a finding
    witness: {dotted.path.string: {"pre": ..., "post": ...}} for every leaf that differs."""
    cfg = config or CanonicalConfig()
    cpre = canonicalize(pre, cfg)
    cpost = canonicalize(post, cfg)
    changes: dict = {}
    _diff(cpre, cpost, (), changes)
    return changes


def _diff(a: Any, b: Any, path: tuple, changes: dict) -> None:
    if isinstance(a, dict) and isinstance(b, dict):
        for k in sorted(set(a) | set(b)):
            _diff(a.get(k, _MISSING), b.get(k, _MISSING), path + (k,), changes)
        return
    if isinstance(a, list) and isinstance(b, list) and len(a) == len(b):
        for i, (x, y) in enumerate(zip(a, b)):
            _diff(x, y, path + (i,), changes)
        return
    if a != b:
        key = ".".join(str(p) for p in path) or "."
        changes[key] = {
            "pre": None if a is _MISSING else a,
            "post": None if b is _MISSING else b,
        }
