"""Toy reference domain -- ~10 mutating tools with hand-verified semantics.

Purpose (CLAUDE.md build spec): debug the mutation machinery and the checker independently of
real-benchmark quirks, on a domain small enough to read in one sitting and whose correctness is
not in question. Deliberately built with the same structural diversity the six operators in
mutation/operators.py need a real site for:

  - guards (an `if ...: raise ...` precondition check)                    -> M-PRECOND sites
  - a whole-function stub target with a clean success return              -> M-PHANTOM sites
  - >=2 unconditional top-level state writes in one effect block          -> M-PARTIAL sites
  - a conditional (branch-nested) compensating write reversing an
    earlier effect elsewhere in the same call graph                      -> M-INVAR sites
  - an effective argument that is actually read in the body               -> M-IGNARG sites
  - a reset routine with several independent field assignments            -> M-RESET sites
  - argument-conditioned branching (resize_inventory's `mode`)
  - a collection-valued effect (audit_log.append, tags.append)
  - a paired write (transfer's debit/credit; acquire/release_lock's count)

State is plain JSON-shaped data (nested dict/list/str/int/float/bool/None) throughout -- no
custom objects, no methods on state values -- because spec/PREDICATE-GRAMMAR.md sec 1 requires a
snapshot to be exactly that, and adapters.base.Adapter.snapshot() must return it unmodified.

Every tool below raises ValueError before any write when a precondition fails (hand-verified: no
mutation happens on the error path -- read each guard's position in the body). Every guard is a
plain top-level `if <cond>: raise ValueError(...)` so mutation/sites.py's structural rule for
M-PRECOND ("a top-level If whose body raises") finds it without special-casing this module.
"""
from __future__ import annotations

import copy
from typing import Any, Optional

__all__ = ["ToyBank", "MUTATING_TOOLS", "make_initial_state"]


def make_initial_state() -> dict:
    """The toy domain's initial snapshot. Deterministic -- calling this twice yields
    byte-identical (deep-equal) dicts, which is what adapters.base.Adapter.fresh_env() requires."""
    return {
        "accounts": {
            "acc_alice": {"owner": "alice", "balance": 100.0, "frozen": False},
            "acc_bob": {"owner": "bob", "balance": 50.0, "frozen": False},
            "acc_carol": {"owner": "carol", "balance": 0.0, "frozen": True},
        },
        "items": {
            "widget": {"qty": 10, "reserved": 2, "tags": ["hardware"]},
            "gadget": {"qty": 5, "reserved": 0, "tags": []},
        },
        "locks": {
            "printer": {"held_by": None, "count": 0},
        },
        "audit_log": [],
    }


class ToyError(ValueError):
    """Raised for every precondition failure in this module. A plain ValueError subclass so
    `except ValueError` at a call site still works; kept distinct so tests can assert on it
    specifically without coupling to ValueError's use elsewhere in the stdlib."""


class ToyBank:
    """One live environment instance. Mirrors what a benchmark's Environment class looks like
    from adapters/tau2.py's point of view: a plain object holding JSON-shaped state, with methods
    that are the agent-visible tools, plus a reset() that is itself part of the advertised
    surface (spec/schema.json's `reset` block)."""

    def __init__(self) -> None:
        self._initial = make_initial_state()
        self.state: dict = copy.deepcopy(self._initial)
        self._audit_seq = 0

    # -- internal helpers, not tools ----------------------------------------------------------

    def _next_audit_entry(self, action: str, **detail: Any) -> dict:
        # `seq` is a monotonic counter -- deliberately analogous to a benchmark's autogenerated
        # id/timestamp field. toy/adapter.py declares state.audit_log.[].seq volatile in its
        # CanonicalConfig so mutation/score.py's canonicalization-gap logic has a real, toy-scale
        # case to exercise (spec/PREDICATE-GRAMMAR.md sec 4, rule 2).
        self._audit_seq += 1
        return {"seq": self._audit_seq, "action": action, **detail}

    # -- tools ----------------------------------------------------------------------------------

    def deposit(self, account_id: str, amount: float) -> dict:
        """Deposit `amount` into `account_id`. The account must exist and must not be frozen,
        and `amount` must be positive. On success, the account's balance increases by exactly
        `amount` and the updated account is returned."""
        account = self.state["accounts"].get(account_id)
        if account is None:
            raise ToyError(f"unknown account: {account_id}")
        if account["frozen"]:
            raise ToyError(f"account is frozen: {account_id}")
        if amount <= 0:
            raise ToyError("amount must be positive")
        account["balance"] = account["balance"] + amount
        return {"account_id": account_id, "balance": account["balance"]}

    def withdraw(self, account_id: str, amount: float) -> dict:
        """Withdraw `amount` from `account_id`. The account must exist, must not be frozen, and
        must hold a balance of at least `amount`; `amount` must be positive. On success, the
        account's balance decreases by exactly `amount` and the updated account is returned."""
        account = self.state["accounts"].get(account_id)
        if account is None:
            raise ToyError(f"unknown account: {account_id}")
        if account["frozen"]:
            raise ToyError(f"account is frozen: {account_id}")
        if amount <= 0:
            raise ToyError("amount must be positive")
        if account["balance"] < amount:
            raise ToyError(f"insufficient balance in {account_id}")
        account["balance"] = account["balance"] - amount
        return {"account_id": account_id, "balance": account["balance"]}

    def transfer(self, from_account: str, to_account: str, amount: float) -> dict:
        """Transfer `amount` from `from_account` to `to_account`. Both accounts must exist and
        must not be frozen, the two account ids must differ, `amount` must be positive, and
        `from_account` must hold a balance of at least `amount`. On success, `from_account`'s
        balance decreases by `amount` and `to_account`'s balance increases by the same amount."""
        src = self.state["accounts"].get(from_account)
        dst = self.state["accounts"].get(to_account)
        if src is None:
            raise ToyError(f"unknown account: {from_account}")
        if dst is None:
            raise ToyError(f"unknown account: {to_account}")
        if from_account == to_account:
            raise ToyError("from_account and to_account must differ")
        if src["frozen"]:
            raise ToyError(f"account is frozen: {from_account}")
        if dst["frozen"]:
            raise ToyError(f"account is frozen: {to_account}")
        if amount <= 0:
            raise ToyError("amount must be positive")
        if src["balance"] < amount:
            raise ToyError(f"insufficient balance in {from_account}")
        # Two unconditional, independent top-level writes -- an M-PARTIAL site pair (they touch
        # different accounts, so deleting either one is a real Partial Effect) and, because the
        # two statements share no data dependency (src is not dst), also the precision-control
        # "reorder independent writes" refactor's target (mutation/equivalence.py).
        src["balance"] = src["balance"] - amount
        dst["balance"] = dst["balance"] + amount
        return {"from_account": from_account, "to_account": to_account, "amount": amount}

    def freeze_account(self, account_id: str) -> dict:
        """Freeze `account_id`, blocking further deposits, withdrawals, and transfers on it.
        The account must exist and must not already be frozen."""
        account = self.state["accounts"].get(account_id)
        if account is None:
            raise ToyError(f"unknown account: {account_id}")
        if account["frozen"]:
            raise ToyError(f"account is already frozen: {account_id}")
        account["frozen"] = True
        return {"account_id": account_id, "frozen": True}

    def unfreeze_account(self, account_id: str) -> dict:
        """Unfreeze `account_id`, restoring normal operation. The account must exist and must
        currently be frozen."""
        account = self.state["accounts"].get(account_id)
        if account is None:
            raise ToyError(f"unknown account: {account_id}")
        if not account["frozen"]:
            raise ToyError(f"account is not frozen: {account_id}")
        account["frozen"] = False
        return {"account_id": account_id, "frozen": False}

    def reserve_item(self, item_id: str, qty: int, account_id: str) -> dict:
        """Reserve `qty` units of `item_id` on behalf of `account_id`. The item and the account
        must exist, `qty` must be positive, and the item's available quantity (qty - reserved)
        must be at least `qty`. On success, the item's reserved count increases by `qty` and an
        audit log entry recording the reservation is appended."""
        item = self.state["items"].get(item_id)
        if item is None:
            raise ToyError(f"unknown item: {item_id}")
        if account_id not in self.state["accounts"]:
            raise ToyError(f"unknown account: {account_id}")
        if qty <= 0:
            raise ToyError("qty must be positive")
        available = item["qty"] - item["reserved"]
        if qty > available:
            raise ToyError(f"insufficient available quantity for {item_id}")
        # Two unconditional top-level writes -- M-PARTIAL pool: the numeric effect and the
        # collection-valued effect (audit_log.append) are independently deletable.
        item["reserved"] = item["reserved"] + qty
        self.state["audit_log"].append(
            self._next_audit_entry("reserve", item_id=item_id, qty=qty, account_id=account_id)
        )
        return {"item_id": item_id, "reserved": item["reserved"]}

    def release_item(self, item_id: str, qty: int) -> dict:
        """Release `qty` previously reserved units of `item_id` back to available inventory.
        The item must exist, `qty` must be positive, and the item's reserved count must be at
        least `qty`. On success, reserved decreases by `qty` and an audit log entry is appended."""
        item = self.state["items"].get(item_id)
        if item is None:
            raise ToyError(f"unknown item: {item_id}")
        if qty <= 0:
            raise ToyError("qty must be positive")
        if item["reserved"] < qty:
            raise ToyError(f"cannot release more than reserved for {item_id}")
        item["reserved"] = item["reserved"] - qty
        self.state["audit_log"].append(self._next_audit_entry("release", item_id=item_id, qty=qty))
        return {"item_id": item_id, "reserved": item["reserved"]}

    def acquire_lock(self, lock_id: str, holder: str) -> dict:
        """Acquire `lock_id` for `holder`. If the lock is currently unheld, it becomes held by
        `holder` with count 1. If it is already held by `holder`, acquisition is reentrant and
        count increases by 1. Acquiring a lock held by a different holder is rejected."""
        if lock_id not in self.state["locks"]:
            raise ToyError(f"unknown lock: {lock_id}")
        lock = self.state["locks"][lock_id]
        if lock["held_by"] is not None and lock["held_by"] != holder:
            raise ToyError(f"lock {lock_id} is held by another holder")
        lock["held_by"] = holder
        lock["count"] = lock["count"] + 1
        return {"lock_id": lock_id, "held_by": lock["held_by"], "count": lock["count"]}

    def release_lock(self, lock_id: str, holder: str) -> dict:
        """Release one level of `lock_id` held by `holder`. The lock must exist, must be held by
        `holder`, and its count must be at least 1. Count decreases by 1; when count reaches 0
        the lock becomes unheld (held_by is cleared) -- the compensating write that reverses
        acquire_lock's `held_by = holder`."""
        if lock_id not in self.state["locks"]:
            raise ToyError(f"unknown lock: {lock_id}")
        lock = self.state["locks"][lock_id]
        if lock["held_by"] != holder:
            raise ToyError(f"lock {lock_id} is not held by {holder}")
        if lock["count"] < 1:
            raise ToyError(f"lock {lock_id} has no outstanding acquisitions")
        lock["count"] = lock["count"] - 1
        if lock["count"] == 0:
            # Conditional, branch-nested compensating write -- the M-INVAR site: deleting this
            # one line leaves count correctly decremented but held_by never cleared, so the lock
            # stays permanently (and invisibly) held. Exactly ARCHITECTURE.md sec 5's example,
            # "release without decrement" generalised one level: here it is release-without-clear.
            lock["held_by"] = None
        return {"lock_id": lock_id, "held_by": lock["held_by"], "count": lock["count"]}

    def resize_inventory(self, item_id: str, delta: int, mode: str) -> dict:
        """Adjust `item_id`'s quantity according to `mode`. `mode` must be one of 'add',
        'remove', or 'set'. 'add' increases qty by `delta`; 'remove' decreases qty by `delta` and
        requires the result stay at or above the item's reserved count; 'set' sets qty to
        `delta` directly and likewise requires `delta` be at least the reserved count. `delta`
        must be non-negative in every mode. Returns the updated item."""
        item = self.state["items"].get(item_id)
        if item is None:
            raise ToyError(f"unknown item: {item_id}")
        if mode not in ("add", "remove", "set"):
            raise ToyError(f"unknown mode: {mode}")
        if delta < 0:
            raise ToyError("delta must be non-negative")
        if mode == "remove" and item["qty"] - delta < item["reserved"]:
            raise ToyError(f"cannot remove below reserved quantity for {item_id}")
        if mode == "set" and delta < item["reserved"]:
            raise ToyError(f"cannot set qty below reserved quantity for {item_id}")
        # Argument-conditioned branching over `mode` -- each arm is a distinct top-level write,
        # so an M-IGNARG mutant that shadows `mode` to a constant collapses all three advertised
        # behaviours into one.
        if mode == "add":
            item["qty"] = item["qty"] + delta
        elif mode == "remove":
            item["qty"] = item["qty"] - delta
        else:
            item["qty"] = delta
        return {"item_id": item_id, "qty": item["qty"], "mode": mode}

    def tag_item(self, item_id: str, tag: str) -> dict:
        """Add `tag` to `item_id`'s tag list. The item must exist, `tag` must be a non-empty
        string, and `tag` must not already be present on the item -- tags are unique per item.
        On success, `tag` is appended to the item's tag list."""
        item = self.state["items"].get(item_id)
        if item is None:
            raise ToyError(f"unknown item: {item_id}")
        if not tag:
            raise ToyError("tag must be non-empty")
        if tag in item["tags"]:
            raise ToyError(f"tag already present on {item_id}: {tag}")
        item["tags"].append(tag)
        return {"item_id": item_id, "tags": list(item["tags"])}

    # -- reset ------------------------------------------------------------------------------

    def reset(self) -> None:
        """Reset the environment to its initial state. Restores accounts, items, locks, and the
        audit log independently -- deliberately four separate assignments rather than one
        `self.state = deepcopy(self._initial)`, so mutation/sites.py has a real per-field M-RESET
        site pool (ARCHITECTURE.md sec 5: 'remove one field assignment from the reset routine')."""
        self.state["accounts"] = copy.deepcopy(self._initial["accounts"])
        self.state["items"] = copy.deepcopy(self._initial["items"])
        self.state["locks"] = copy.deepcopy(self._initial["locks"])
        self.state["audit_log"] = copy.deepcopy(self._initial["audit_log"])
        self._audit_seq = 0


# Tool name -> whether it mutates state. Every tool above does; kept as an explicit table (not
# "every public method") so toy/adapter.py's list_tools() has one place to cite, mirroring
# CLAUDE.md's counting rule (mutates_state is authoritative, never inferred from a naming
# convention). `reset` is deliberately excluded -- it is the reset routine, not an agent-visible
# tool, matching how tau2's Environment.reset() is not itself a tool in Environment.tools.
MUTATING_TOOLS: tuple[str, ...] = (
    "deposit",
    "withdraw",
    "transfer",
    "freeze_account",
    "unfreeze_account",
    "reserve_item",
    "release_item",
    "acquire_lock",
    "release_lock",
    "resize_inventory",
    "tag_item",
)
